export const feedbackToAgencyMap: Record<string, string> = {
  covid: 'MOH',
  Forward: 'PMO',
  budget: 'MOF',
  community: 'MCCY',
  social: 'MCCY',
  economy: 'MOF',
  education: 'MOE',
  environment: 'NEA',
  foreign: 'MFA',
  healthcare: 'MOH',
  housing: 'MND',
  manpower: 'MOM',
  municipal: 'MND',
  rally: 'PMO',
  transport: 'MOT',
  reach: 'MCI',
  governance: 'pmo',
}
